services:
  auth_api:
    image: registry.digitalocean.com/gg-match-registry/gg-match-api:auth
    container_name: ggmatch_auth
    ports:
      - "80:8000"
    volumes:
      - ./auth-service:/app 
    depends_on:
      - postgres_db

  #BASES DE DATOS
  postgres_db:
    image: postgres:15-alpine
    container_name: ggmatch_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo_db:
    image: mongo:6.0
    container_name: ggmatch_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: superpassword123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis_db:
    image: redis:7-alpine
    container_name: ggmatch_redis
    restart: always
    ports:
      - "6379:6379"

  tournament_api:
    image: registry.digitalocean.com/gg-match-registry/gg-match-api:tournament
    container_name: ggmatch_tournament
    ports:
      - "8001:8000"
    environment:
      - MONGO_URL=mongodb://admin:superpassword123@mongo_db:27017
    depends_on:
      - mongo_db

volumes:
  postgres_data:
  mongo_data:
