name: CI/CD Pipeline GG-Match

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar CLI de DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Iniciar sesión en el Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Construir imagen Auth
        run: docker build -t registry.digitalocean.com/gg-match-registry/gg-match-api:auth ./auth-service

      - name: Subir imagen Auth
        run: docker push registry.digitalocean.com/gg-match-registry/gg-match-api:auth

      - name: Construir imagen Tournament
        run: docker build -t registry.digitalocean.com/gg-match-registry/gg-match-api:tournament ./tournament-service

      - name: Subir imagen Tournament
        run: docker push registry.digitalocean.com/gg-match-registry/gg-match-api:tournament

      - name: Construir imagen Stats
        run: docker build -t registry.digitalocean.com/gg-match-registry/gg-match-api:stats ./stats-service

      - name: Subir imagen Stats
        run: docker push registry.digitalocean.com/gg-match-registry/gg-match-api:stats

      - name: Instalar doctl (DigitalOcean CLI)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Conectar al Clúster K8s
        run: doctl kubernetes cluster kubeconfig save gg-match-cluster

      - name: Reiniciar Microservicios (Para descargar código nuevo)
        run: |
          kubectl rollout restart deployment auth-deployment
          kubectl rollout restart deployment tournament-deployment
          kubectl rollout restart deployment stats-deployment