name: CI/CD Pipeline GG-Match

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar CLI de DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Iniciar sesión en el Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Construir imagen Auth
        run: docker build -t registry.digitalocean.com/gg-match-registry/gg-match-api:auth ./auth-service

      - name: Subir imagen Auth
        run: docker push registry.digitalocean.com/gg-match-registry/gg-match-api:auth

      - name: Construir imagen Tournament
        run: docker build -t registry.digitalocean.com/gg-match-registry/gg-match-api:tournament ./tournament-service

      - name: Subir imagen Tournament
        run: docker push registry.digitalocean.com/gg-match-registry/gg-match-api:tournament

      - name: Desplegar en el Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            cd ~/GG-Match
            
            git pull origin main

            # Descargar ambas imágenes frescas con sus nuevas etiquetas
            docker pull registry.digitalocean.com/gg-match-registry/gg-match-api:auth
            docker pull registry.digitalocean.com/gg-match-registry/gg-match-api:tournament
            
            # Reiniciar todo
            docker-compose up -d